program: 4_Medical_class_incremental_cosine_Deepinversion.py
method: bayes
metric:
    goal: maximize
    name: Best Acc
parameters:
    lr:
        value: 0.01
    lr_verifier:
        value: 0.01
    batch_size_1: 
        value: 40
    directory:
        value: sweep_phase1_training
    ckp_prefix:
        value: class_incremental_MR_LFAD_cosine_small
    ckp_prefix_verifier:
        value: class_incremental_MR_LFAD_cosine_small_VGG_2
    random_seed:
        value: 1993
    nb_cl_fg:
        value: 2 
    nb_cl:
        value: 1 
    nb_phases: 
        value: 2 
    num_classes: 
        value: 14
    epochs: 
        value: 70
    rs_ratio: 
        value: 0.66
    dist:
        value: 0.7 
    K: 
        value: 1
    lw_mr: 
        value: 1
    bs: 
        value: 40 
    setting_id: 
        value: 1 
    generation_lr: 
        value: 0.25
    adi_scale: 
        value: 0.0 
    tv_l2: 
        value: 0.001 
    r_feature: 
        value: 0.2
    l2: 
        value: 0.01
    cosine_normalization:
        value: True
    small_model:
        value: True
    imprint_weights:
        value: True
    adapt_lamda:
        value: True
    less_forget:
        value: True
    mr_loss:
        value: True
    do_flip:
        value: True
    resume:
        value: True
    sampler_type:
        value: paper2
    validate:
        value: True
    mode:
        value: paper_2
    add_data:
        value: True
    save_samples_dir:
        value: ./saved_Sample_3_2
    type_of_verifier:
        value: VGG
    use_mean_initialization:
        value: true
    beta_2:
        value: 0.09
    random_label:
        value: true
    cuda_number:
        value: 1
    generate_more:
        value: true
    alpha_3:
        value: 1
    CL:
        value: 1
    ro:
        values: [0.9, 0.99, 0.999]
    temprature:
        values: [1,5,10]
early_terminate:
    type: hyperband
    s: 2
    eta: 3
    max_iter: 30    
project: CL